### ISSUE TITLE
FileInput error container issue using AJAX in Internet Explorer

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-widgets#308] opened 2016-06-21 03:21 UTC
Hello,

I'm using the `FileInput` widget on my projects and found an issue in Internet Explorer (version 10 and 11) that doesn't occur in other browsers.

Basically I'm using the input without preview to upload one file with AJAX.
Here's my view code :

``` php
<?= $form->field($model, 'mailFile')
    ->widget(FileInput::classname(), [
            'options' => ['id' => 'mailFile'],
            'pluginOptions' => [
                    'showPreview' => false,
                    'uploadUrl' => Url::to(['/mail/regular-file-upload']),
                    'layoutTemplates' => ['main1' => "
                            <div class=\"kv-upload-progress hide\"></div>\n
                            <p id=\"mailFile-caption\"></p>\n
                            <div class=\"input-group {class}\">\n
                                <div class=\"input-group-btn\">\n{remove}\n{cancel}\n{upload}\n{browse}\n</div>\n
                            /div>\n
                            <div id=\"mailFile-error\"></div>
                    "],
                    'elCaptionText' => '#mailFile-caption',
                    'elErrorContainer' => '#mailFile-error',
            ],
    ])
?>
```

The model behind the form has a rule to check extension and MIME type and allow PDF files only.

``` php
[['mailFile'], 'file', 'checkExtensionByMimeType' => false, 'extensions' => ['pdf'], 'mimeTypes' => 'application/pdf'],
```

The controller validate the form through the AJAX post and return a JSON response

``` php
public function actionRegularFileUpload()
    {
        $response = array();

        $model = new OrderForm();
        $mailFileUploaded = $model->uploadFile('mailFile'); // This include a call to UploadedFile::getInstance to get the file

        if ($mailFileUploaded) {
            // Validate mail file in form model
            if ($model->validate(['mailFile'])) {
                $model->saveFile('mailFile');
            } else {
                $response['error'] = $model->getFirstError('mailFile');
            }
        }

        // Encode response in JSON
        return Json::encode($response);
    }
```

So what is expected when we upload something different from a PDF file is an error message in the `elErrorContainer` pushed by the AJAX call response.
This is indeed happening in Chrome or Opera
![image](https://cloud.githubusercontent.com/assets/5624541/16216502/fcbf0874-37b6-11e6-8019-0f2b01aa49c2.png)

But in Internet Explorer, there's a brief red flash as if the error message was being rendered and directly after nothing
![image](https://cloud.githubusercontent.com/assets/5624541/16216974/0525b43c-37bb-11e6-8d97-c0977945d5ac.png)

Can you help with that issue ? I've been checking everything in my browser, clearing cache, updating plugin...

PS : I'm posting this issue since I use the Yii2 widget but I'm pretty sure this issue is related to kartik-v/bootstrap-fileinput plugin.

**Comment by Lyococ** [comment] 2017-04-20 16:56
Incluir el content='IE=10' para que tome los cambios del fileinput, mas información https://blogs.technet.microsoft.com/techesp/2014/11/11/compatibilidad-en-internet-explorer-11-modo-documento-vista-de-compatibilidad-y-modo-empresas/

**Comment by kartik-v** [comment] 2017-04-21 09:02
@gael-wogenstahl can you check if you have the latest release of the extension and are facing this issue still?

**Comment by kartik-v** [comment] 2017-12-27 02:28
Cannot reproduce the issue myself. Closing this. Let know on the above and will reopen if you can report.

**Closed by kartik-v** 2017-12-27 02:28 UTC
